site_name: Mokka Studios - Documentation
site_url: https://example.com/
repo_name: Go to repository

nav:
  - Home: index.md
  - About: about.md

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/logo.png
  font:
    text: Lato
  palette:

    - media: "(prefers-color-scheme: dark)"
      primary: "black"
      scheme: slate

  features:
    - navigation.tabs
    - navigation.path
    - navigation.top
    - navigation.footer
  
copyright: Copyright © 2024 Mokka Studios S.r.l. All rights reserved.

extra:
  generator: false
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/mokkastudios/mokkastudios-docs
    name: Go to repository

plugins:
  - git-revision-date-localized:
      exclude:
        - blog/archive/*
        - blog/category/*
      enable_creation_date: true
      type: timeago
  - git-committers:
      # enabled: !ENV [CI, false]
      repository: mokkastudios/mokkastudios-docs
      branch: master
  - social:
      cards_layout_options:
        background_color: black
        color: "#ffffff"
