site_name: Mokka Studios - Documentation
site_url: https://example.com/
repo_name: Go to repository

nav:
  - Home: index.md
  - Project management:
    - Project initialization:
      - project-management/project-initialization/index.md
      - Linear: project-management/project-initialization/linear.md
      - Slack: project-management/project-initialization/slack.md
      - Google Drive: project-management/project-initialization/drive.md
      - Google Calendar: project-management/project-initialization/calendar.md
      - Figma: project-management/project-initialization/figma.md
      - Github: project-management/project-initialization/github.md
      - Stores: project-management/project-initialization/stores.md
    - Other:
      - project-management/other/index.md
      - Resources: project-management/other/resources.md
      - Credentials: project-management/other/credentials.md

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/logo.png
  font:
    text: Lato
  palette:

    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate

  features:
    - navigation.tabs
    - navigation.path
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tracking
    - toc.follow
    - content.tooltips
    - content.code.copy
  
copyright: Copyright © 2024 Mokka Studios S.r.l. All rights reserved.

extra:
  generator: false
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/mokkastudios/mokkastudios-docs
    name: Go to repository

plugins:
  - git-revision-date-localized:
      exclude:
        - blog/archive/*
        - blog/category/*
      enable_creation_date: true
      type: timeago
  # - git-committers:
  #     repository: mokkastudios/mokkastudios-docs
  #     branch: master
  # - social:
  #     cards_layout_options:
  #       background_color: black
  #       color: "#ffffff"

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink_title: Anchor link to this section for reference
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets